### PR TITLE
update to serde 1.0

### PR DESCRIPTION
**Pull request by Eh2406**

### CODE REVIEW

**Comment by drusellers** [comment]
+1

**Comment by drusellers** [comment]
yes, this branch let me use the project. WHOOT

**Review by dtolnay — APPROVED** [review]

**Comment by ishitatsuyuki** [comment]
@AndyBarron friendly ping. Can you merge?

**Comment by andybarron** [comment]
Hi there! I'll merge over the weekend as soon as I have time to also deploy a new version to Cargo :)

Sorry for the delay, folks :heart:

**Comment by Eh2406** [comment]
Ping?

**Comment by cars10** [comment]
*bump*

**Comment by Eh2406** [comment]
Ping?

**Comment by cars10** [comment]
I guess this project is dead?

**Comment by Eh2406** [comment]
Ping?

**Comment by panicbit** [comment]
This is blocking me from publish a crate :disappointed:

**Comment by Besler** [comment]
Hate to see this project die. I was able to get  https://github.com/baysmith/preferences-rs working with `serde = "1.1"`. Any chance to bring back?

**Comment by jngls** [comment]
Damn, just been grinding on this for half a day thinking I was doing something wrong.

**Comment by giotiskl** [comment]
bump in hopes of a merge

**Pull request merged**
